### PR TITLE
correcting typo allows darwin to work

### PR DESCRIPTION
**Pull request by metayan**
Have been trying to get this to work for ages.
Your recent claw-git2 example gave me a hint where to check.
Thanks.

### CODE REVIEW

**Comment by borodust** [comment]
JEZUZ
Thanks! Although typo is slightly in a different place, but with the same energy.

**Comment by borodust** [comment]
Typo fixed. This is the place it leaked from: https://github.com/borodust/bodge-glfw/blob/d9b3b53bd978e986d859d8db4ab6e06c8f723a9d/src/claw.lisp#L10

Please, let me know if updated bindings didn't break anything.

**Comment by borodust** [comment]
I've got a confirmation bindigns work. Thanks again!

**Comment by metayan** [comment]
Yes, they work on Darwin. Tested with sucle.

**Pull request closed without merging**
